version: "3.5"
services:
  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      # root & logs
      - ./web:/data/wwwroot
      - ./logs/nginx:/var/log/nginx
      # nginx
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./services/ssl:/root/.acme.sh/
      # vhost-gen
      - ./services/nginx/vhost-gen/conf.yml:/etc/vhost-gen/conf.yml
      - ./services/nginx/vhost-gen/nginx.yml:/etc/vhost-gen/templates/nginx.yml
      # share
      - ./share:/share
    environment:
      ENABLE_CRONTAB: "true"
      TZ: ${TZ}
      DP_Id: ${DP_ID}
      DP_Key: ${DP_KEY}
    restart: on-failure

  apache:
    container_name: apache
    build:
      context: ./services/apache
      args:
        APACHE_VERSION: ${APACHE_VERSION}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
    volumes:
      # root & logs
      - ./web:/data/wwwroot
      - ./logs/apache:/var/log/nginx
      # apache
      - ./services/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./services/apache/conf.d:/usr/local/apache2/conf/vhost
      - ./services/ssl:/usr/local/apache2/conf/ssl
      # vhost-gen
      - ./services/apache/vhost-gen/conf.yml:/etc/vhost-gen/conf.yml
      - ./services/apache/vhost-gen/apache24.yml:/etc/vhost-gen/templates/apache24.yml
      # share
      - ./share:/share
    environment:
      ENABLE_CRONTAB: "true"
      TZ: ${TZ}
    restart: on-failure

  php:
    container_name: php
    build:
      context: ./services/php
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        TZ: "$TZ"
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
    expose:
      - 9501
    volumes:
      # root
      - ./web:/data/wwwroot
      # conf
      - ./services/php/php.ini:/usr/local/etc/php/php.ini
      - ./services/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      # log
      - ./logs/php:/var/log/php
      # data
      - ./data/composer:/tmp/composer
      # share
      - ./share:/share
    restart: on-failure
    cap_add:
      - SYS_PTRACE

  mysql:
    container_name: mysql
    image: ${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ./services/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./data/mysql:/var/lib/mysql
      # share
      - ./share:/share
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      TZ: "$TZ"
    restart: on-failure

  postgresql:
    container_name: postgresql
    image: ${POSTGRESQL_VERSION}
    ports:
      - "${POSTGRESQL_HOST_PORT}:5432"
    volumes:
      - ./services/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./data/postgresql:/var/lib/postgresql/data
      # share
      - ./share:/share
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "${POSTGRESQL_PASSWORD}"
      TZ: "$TZ"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'

networks:
  default:
    name: dnmp
